
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8
      sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall git   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git http-parser curl mongodb; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/swift-3.0-release/ubuntu1404/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-3.0-RELEASE-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=swift-3.0-RELEASE-ubuntu14.04/usr/bin:$PATH    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install clang libicu-dev libkqueue-dev libtool libcurl4-openssl-dev libbsd-dev libblocksruntime-dev mongodb ; fi
  - git clone https://github.com/IBM-Swift/todolist-tests
  - cd todolist-tests && cd ..
  - mv todolist-tests Tests
  - sudo mkdir -p /data/db
  - sudo mkdir -p ~/log
  - sudo mongod --fork --logpath ~/log/mongodb.log
  - sleep 45

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift test ; fi
